---
pipeline:
  main_template: template-repo/ci/templates/staging-prod/pipeline_main_template.yml
  groups:
    - name: Staging
      template: template-repo/ci/templates/staging-prod/pipeline_stage_template.yml
      environments:
      - name: Staging1
    - name: Production
      template: template-repo/ci/templates/staging-prod/pipeline_stage_template.yml
      trigger_job_template: template-repo/ci/templates/staging-prod/trigger.yml
      environments:
      - name: West1
